accel: 83.2421875
auto_rotate: false
const_speed: 1
model: 5
native_res_factor: 1016.0
pen_pos_down: 79
pen_pos_up: 25
pen_rate_lower: 50
pen_rate_raise: 63.39062500000001
profile_name: aa
random_start: false
reordering: 0
report_time: false
resolution: 1
speed_pendown: 98.67262569832403
speed_penup: 69.44921875
svg_file: null
